# Generated by Django 5.2.15 on 2026-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual')], default='individual', max_length=20),
        ),
    ]
