# Generated by Django 5.2.15 on 2026-06-23 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
        ('exchange', '0011_alter_swaprequest_options_alter_item_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['swap_request', 'is_read'], name='chat_messag_swap_re_f0a4ed_idx'),
        ),
    ]
