# Generated by Django 5.2.15 on 2026-06-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_remove_center_center_type_and_more'),
        ('exchange', '0010_alter_item_options_item_address_item_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swaprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_swapped'], name='exchange_it_is_swap_09a5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['status'], name='exchange_sw_status_8156cd_idx'),
        ),
        migrations.AddIndex(
            model_name='swaprequest',
            index=models.Index(fields=['-created_at'], name='exchange_sw_created_2dd061_idx'),
        ),
        migrations.AddConstraint(
            model_name='swaprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('item', 'sender'), name='unique_pending_swap_request_per_item_sender'),
        ),
    ]
